### PR TITLE
CodeCov support

### PR DESCRIPTION
**Pull request by Bob-Chen222**
**Description of changes:**

- ```proj cmake``` will create two separate build folders. build and build_codecov. Additional flag FF_USE_CODE_COVERAGE is added to achieve the optional instrumentation in cmake
- use ```proj test --coverage``` will generate coverage info in terminal. ```proj test --coverage --browser``` will run the report in user's browser(if have one)
- filtered the coverage information and currently, only code in lib/ will be covered (can change the scope of coverage very easily if needed)
- codecov is supported. The codecov report can be visualized and PR in the future will support automatic code coverage comment

- - -
This change is [Reviewable](https://reviewable.io/reviews/lockshaw/proj/6)

### CODE REVIEW

**Review by lockshaw — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/lockshaw/proj/6)* status: all files reviewed, 4 unresolved discussions (waiting on @Bob-Chen222)

___
*[`proj/__main__.py` line 102 at r1](https://reviewable.io/reviews/lockshaw/proj/6#-Nz5cP6wBwI1hz1TBQOr:-Nz5cP6xBAQ3TT1ZOdfU:b-3gvwog) ([raw file](https://github.com/lockshaw/proj/blob/61b3912fa2a4b3be34dbac4a22d63f52ace9290f/proj/__main__.py#L102)):*
> ```Python
>         env=os.environ,
>         shell=config.cmake_require_shell,
>     )
> ```

Pull duplicated code out into a separate function--I think a lot of this is exactly the same as the code above



_Code quote:_
```Python
    cmake_args += ["-DFF_USE_CODE_COVERAGE=ON"]
    if args.force and config.cov_dir.exists():
        shutil.rmtree(config.cov_dir)
    config.cov_dir.mkdir(exist_ok=True, parents=True)
    subprocess_check_call(
        [
            "cmake",
            *cmake_args,
            "..",
        ],
        stderr=sys.stdout,
        cwd=config.cov_dir,
        env=os.environ,
        shell=config.cmake_require_shell,
    )
```
___
*[`proj/__main__.py` line 131 at r1](https://reviewable.io/reviews/lockshaw/proj/6#-Nz5cg5K5YMb7EhzjvLJ:-Nz5cg5K5YMb7EhzjvLK:undefined) ([raw file](https://github.com/lockshaw/proj/blob/61b3912fa2a4b3be34dbac4a22d63f52ace9290f/proj/__main__.py#L131)):*
> ```Python
>     if args.coverage:
>         print("will use separate dir for code coverage")
>         cwd = config.cov_dir
> ```





_Suggestion:_
```Python
    if args.coverage:
        cwd = config.cov_dir
    else:
        cwd = config.build_dir
```
___
*[`proj/__main__.py` line 182 at r1](https://reviewable.io/reviews/lockshaw/proj/6#-Nz5daG454ZybcFyQBtX:-Nz5daG454ZybcFyQBtY:bp6pdf4) ([raw file](https://github.com/lockshaw/proj/blob/61b3912fa2a4b3be34dbac4a22d63f52ace9290f/proj/__main__.py#L182)):*
> ```Python
>                 "--remove",
>                 "main_coverage.info",
>                 "/nix/store/*",
> ```

Why remove everything under `/nix/store` instead of only including things in the repo?
___
*[`proj/lockshaw_config.py` line 40 at r1](https://reviewable.io/reviews/lockshaw/proj/6#-Nz5dGNdEgcxqekQ9l6d:-Nz5dGNdEgcxqekQ9l6e:b-ejd7n7) ([raw file](https://github.com/lockshaw/proj/blob/61b3912fa2a4b3be34dbac4a22d63f52ace9290f/proj/lockshaw_config.py#L40)):*
> ```Python
>     @property
>     def cov_dir(self) -> Path:
>         return self.base / "build_codecov"
> ```

Can we instead have things in `build/normal` and `build/codecov`? Mainly to avoid cluttering the root of the repo, and also that way we don't have to change the .gitignore, etc.

**Review by Bob-Chen222 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/lockshaw/proj/6)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @lockshaw)

___
*[`proj/__main__.py` line 102 at r1](https://reviewable.io/reviews/lockshaw/proj/6#-Nz5cP6wBwI1hz1TBQOr:-Nz6BY89EcftF1MR548J:b-896fix) ([raw file](https://github.com/lockshaw/proj/blob/61b3912fa2a4b3be34dbac4a22d63f52ace9290f/proj/__main__.py#L102)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Pull duplicated code out into a separate function--I think a lot of this is exactly the same as the code above
</blockquote></details>

Done.
___
*[`proj/__main__.py` line 131 at r1](https://reviewable.io/reviews/lockshaw/proj/6#-Nz5cg5K5YMb7EhzjvLJ:-Nz67JxB9nCCN_6S7z2w:b-896fix) ([raw file](https://github.com/lockshaw/proj/blob/61b3912fa2a4b3be34dbac4a22d63f52ace9290f/proj/__main__.py#L131)):*
> ```Python
>     if args.coverage:
>         print("will use separate dir for code coverage")
>         cwd = config.cov_dir
> ```

Done.
___
*[`proj/__main__.py` line 182 at r1](https://reviewable.io/reviews/lockshaw/proj/6#-Nz5daG454ZybcFyQBtX:-Nz6BV4y-wCJG7UZmJss:b-896fix) ([raw file](https://github.com/lockshaw/proj/blob/61b3912fa2a4b3be34dbac4a22d63f52ace9290f/proj/__main__.py#L182)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Why remove everything under `/nix/store` instead of only including things in the repo?
</blockquote></details>

Done.
___
*[`proj/lockshaw_config.py` line 40 at r1](https://reviewable.io/reviews/lockshaw/proj/6#-Nz5dGNdEgcxqekQ9l6d:-Nz67HQ10ykxI5NMPVtx:b-896fix) ([raw file](https://github.com/lockshaw/proj/blob/61b3912fa2a4b3be34dbac4a22d63f52ace9290f/proj/lockshaw_config.py#L40)):*
<details><summary><i>Previously, lockshaw (Colin Unger) wrote…</i></summary><blockquote>

Can we instead have things in `build/normal` and `build/codecov`? Mainly to avoid cluttering the root of the repo, and also that way we don't have to change the .gitignore, etc.
</blockquote></details>

Done.

**Review by lockshaw — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/lockshaw/proj/6)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Bob-Chen222)

___
*[`proj/__main__.py` line 99 at r2](https://reviewable.io/reviews/lockshaw/proj/6#-Nz6bbef53ebnZsXctQb:-Nz6bbef53ebnZsXctQc:b-vfhapg) ([raw file](https://github.com/lockshaw/proj/blob/976829cb560ca926d8173aeb9533bd698edbd0d6/proj/__main__.py#L99)):*
> ```Python
>         
>     cmake_args += ["-DFF_USE_CODE_COVERAGE=ON"]
>     cmake(cmake_args, config, True)
> ```

Probably better because it doesn't mutate `cmake_args` which makes it easier to get confused, but this is a very minor detail



_Suggestion:_
```Python
    cmake(cmake_args + ["-DFF_USE_CODE_COVERAGE=ON"], config, True)
```

**Review by lockshaw — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/lockshaw/proj/6)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Bob-Chen222)

**Pull request merged**
